### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by Krops** [aschober/vinyl-cast#22]
Can't run app on android tv. Would be good to listen turntable on tv.

**Comment by Krops** [comment]
I tried to run it on Android TV emulator and got. Does anyone know what could be the reason?
```
2022-01-18 17:19:39.489 27811-27811/tech.schober.vinylcast.github.debug W/DynamiteModule: Local module descriptor class for com.google.android.gms.cast.framework.dynamite not found.
2022-01-18 17:19:39.489 27811-27811/tech.schober.vinylcast.github.debug I/DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:0
2022-01-18 17:19:39.490 27811-27811/tech.schober.vinylcast.github.debug D/AndroidRuntime: Shutting down VM
2022-01-18 17:19:39.493 27811-27811/tech.schober.vinylcast.github.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.schober.vinylcast.github.debug, PID: 27811
    java.lang.RuntimeException: Unable to create application tech.schober.vinylcast.VinylCastApplication: java.lang.RuntimeException: com.google.android.gms.cast.framework.zzat: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: com.google.android.gms.cast.framework.zzat: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@20.1.0:8)
        at tech.schober.vinylcast.VinylCastApplication.onCreate(VinylCastApplication.java:24)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: com.google.android.gms.cast.framework.zzat: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
        at com.google.android.gms.internal.cast.zzm.zzf(com.google.android.gms:play-services-cast-framework@@20.1.0:7)
        at com.google.android.gms.internal.cast.zzm.zza(com.google.android.gms:play-services-cast-framework@@20.1.0:1)
        at com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@20.1.0:4)
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@20.1.0:7)
        at tech.schober.vinylcast.VinylCastApplication.onCreate(VinylCastApplication.java:24) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.0:65)
        at com.google.android.gms.internal.cast.zzm.zzf(com.google.android.gms:play-services-cast-framework@@20.1.0:2)
        at com.google.android.gms.internal.cast.zzm.zza(com.google.android.gms:play-services-cast-framework@@20.1.0:1) 
        at com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@20.1.0:4) 
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@20.1.0:7) 
        at tech.schober.vinylcast.VinylCastApplication.onCreate(VinylCastApplication.java:24) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2022-01-18 17:19:39.520 27811-27811/tech.schober.vinylcast.github.debug I/Process: Sending signal. PID: 27811 SIG: 9
```
<img width="1792" alt="Screenshot 2022-02-12 at 11 16 55" src="https://user-images.githubusercontent.com/7998052/153705371-9e205713-495f-43d7-9730-cdbb6f9f4501.png">
